openapi: 3.1.0
info:
  title: PACT API Specification
  version: 2.2.1-wip1
paths:
  /2/footprints/{id}:
    get:
      summary: Action GetFootprint
      operationId: get-footprint
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    $ref: '#/components/schemas/ProductFootprint'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
      security:
      - BearerAuth: []
  /2/footprints:
    get:
      summary: Action ListFootprints
      operationId: list-footprints
      parameters:
      - name: limit
        in: query
        schema:
          type: integer
          format: uint
          minimum: 0
      - name: '$filter'
        in: query
        description: Syntax as defined by the ODatav4 specification
        allowEmptyValue: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          headers:
            link:
              description: Link header to next result set. See Tech Specs section 6.6.1
              schema:
                type: string
              example: https://api.example.com/2/footprints?[...]
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductFootprint'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
      security:
      - BearerAuth: []
  /2/events:
    post:
      operationId: post_event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PathfinderEvent'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDenied'
        '501':
          description: Not implemented.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
      security:
      - BearerAuth: []
components:
  schemas:
    ProductFootprint:
      description: Data Type "ProductFootprint" of Tech Spec Version 2
      type: object
      required:
      - id
      - specVersion
      - version
      - created
      - status
      - comment
      - companyName
      - companyIds
      - productDescription
      - productIds
      - productCategoryCpc
      - productNameCompany
      - pcf
      properties:
        id:
          type: string
          format: uuid
        specVersion:
          $ref: '#/components/schemas/VersionString'
        precedingPfIds:
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
          uniqueItems: true
        version:
          type: integer
          format: int32
          maximum: 2147483647
          minimum: 0
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - Active
            - Deprecated
        statusComment:
          type: string
        validityPeriodStart:
          type: string
          format: date-time
        validityPeriodEnd:
          type: string
          format: date-time
        companyName:
          $ref: '#/components/schemas/NonEmptyString'
        companyIds:
          $ref: '#/components/schemas/CompanyIdSet'
        productDescription:
          type: string
        productIds:
          $ref: '#/components/schemas/ProductIdSet'
        productCategoryCpc:
          $ref: '#/components/schemas/NonEmptyString'
        productNameCompany:
          $ref: '#/components/schemas/NonEmptyString'
        comment:
          type: string
        pcf:
          $ref: '#/components/schemas/CarbonFootprint'
    VersionString:
      type: string
      minLength: 5
      pattern: '^\d+\.\d+\.\d+(-\d{8})?$'
    NonEmptyString:
      type: string
      minLength: 1
    CompanyIdSet:
      type: array
      items:
        type: string
        pattern: '^([uU][rR][nN]):'
      minItems: 1
      uniqueItems: true
    GenericURN:
      type: string
      pattern: '^([uU][rR][nN]):'
    ProductIdSet:
      type: array
      items:
        type: string
        pattern: '^([uU][rR][nN]):'
      minItems: 1
      uniqueItems: true
    CarbonFootprint:
      description: Data Type "CarbonFootprint" of Spec Version 2
      type: object
      required:
      - biogenicCarbonContent
      - boundaryProcessesDescription
      - characterizationFactors
      - crossSectoralStandardsUsed
      - declaredUnit
      - exemptedEmissionsDescription
      - exemptedEmissionsPercent
      - fossilCarbonContent
      - fossilGhgEmissions
      - ipccCharacterizationFactorsSources
      - pCfExcludingBiogenic
      - packagingEmissionsIncluded
      - productOrSectorSpecificRules
      - referencePeriodEnd
      - referencePeriodStart
      - unitaryProductAmount
      oneOf:
      - oneOf:
        - required:
          - geographyRegionOrSubregion
        - required:
          - geographyCountry
        - required:
          - geographyCountrySubdivision
      - not:
          anyOf:
          - required:
            - geographyRegionOrSubregion
          - required:
            - geographyCountry
          - required:
            - geographyCountrySubdivision
      properties:
        geographyRegionOrSubregion:
          $ref: '#/components/schemas/UNRegionOrSubregion'
        geographyCountry:
          $ref: '#/components/schemas/ISO3166CC'
        geographyCountrySubdivision:
          $ref: '#/components/schemas/NonEmptyString'
        declaredUnit:
          $ref: '#/components/schemas/DeclaredUnit'
        unitaryProductAmount:
          $ref: '#/components/schemas/PositiveNonZeroDecimal'
        pCfExcludingBiogenic:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        pCfIncludingBiogenic:
          $ref: '#/components/schemas/Decimal'
        fossilGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        fossilCarbonContent:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        biogenicCarbonContent:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        dLucGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        landManagementGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        otherBiogenicGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        iLucGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        biogenicCarbonWithdrawal:
          $ref: '#/components/schemas/NegativeOrZeroDecimal'
        aircraftGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        characterizationFactors:
          $ref: '#/components/schemas/CharacterizationFactors'
        ipccCharacterizationFactorsSources:
          $ref: '#/components/schemas/IpccCharacterizationFactorsSources'
        crossSectoralStandardsUsed:
          $ref: '#/components/schemas/CrossSectoralStandardSet'
        productOrSectorSpecificRules:
          $ref: '#/components/schemas/ProductOrSectorSpecificRuleSet'
        biogenicAccountingMethodology:
          $ref: '#/components/schemas/BiogenicAccountingMethodology'
        boundaryProcessesDescription:
          type: string
        referencePeriodStart:
          type: string
          format: date-time
        referencePeriodEnd:
          type: string
          format: date-time
        secondaryEmissionFactorSources:
          $ref: '#/components/schemas/EmissionFactorDSSet'
        exemptedEmissionsPercent:
          $ref: '#/components/schemas/ExemptedEmissionsPercent'
        exemptedEmissionsDescription:
          type: string
        packagingEmissionsIncluded:
          type: boolean
        packagingGhgEmissions:
          $ref: '#/components/schemas/PositiveOrZeroDecimal'
        allocationRulesDescription:
          type: string
        uncertaintyAssessmentDescription:
          type: string
        primaryDataShare:
          $ref: '#/components/schemas/Percent'
        dqi:
          $ref: '#/components/schemas/DataQualityIndicators'
        assurance:
          $ref: '#/components/schemas/Assurance'
    DeclaredUnit:
      description: Data Type "DeclaredUnit" of Spec Version 2
      type: string
      enum:
      - liter
      - kilogram
      - cubic meter
      - kilowatt hour
      - megajoule
      - ton kilometer
      - square meter
    PositiveNonZeroDecimal:
      type: string
      pattern: ^[+]?(\d*[1-9]\d*)(\.\d+)?|(0+\.\d*[1-9]\d*)$
    PositiveOrZeroDecimal:
      type: string
      pattern: ^[+]?\d+(\.\d+)?$
      comment: A positive or zero decimal number.
    Decimal:
      type: string
      pattern: ^[+-]?\d+(\.\d+)?$
    NegativeOrZeroDecimal:
      type: string
      pattern: ^(-\d+(\.\d+)?)|0+(\.0+)?$
    NegativeNonZeroDecimal:
      type: string
      pattern: ^-((\d*[1-9]\d*)(\.\d+)?|(0+\.\d*[1-9]\d*))$
    CharacterizationFactors:
      type: string
      enum:
      - AR5
      - AR6
    IpccCharacterizationFactorsSources:
      type: array
      items:
        type: string
        pattern: ^AR\d+$
      minItems: 1
      uniqueItems: true
    IpccCharacterizationFactorsSource:
      type: string
      pattern: ^AR\d+$
    CrossSectoralStandardSet:
      type: array
      items:
        description: Data Type "CrossSectoralStandard" of Spec Version 2
        type: string
        enum:
        - GHG Protocol Product standard
        - ISO Standard 14067
        - ISO Standard 14044
      minItems: 1
      uniqueItems: true
    CrossSectoralStandard:
      description: Data Type "CrossSectoralStandard" of Spec Version 2
      type: string
      enum:
      - GHG Protocol Product standard
      - ISO Standard 14067
      - ISO Standard 14044
    ProductOrSectorSpecificRuleSet:
      type: array
      items:
        type: object
        required:
        - operator
        - ruleNames
        properties:
          operator:
            $ref: '#/components/schemas/ProductOrSectorSpecificRuleOperator'
          ruleNames:
            $ref: '#/components/schemas/NonEmptyStringVec'
          otherOperatorName:
            anyOf:
            - $ref: '#/components/schemas/NonEmptyString'
            - type: 'null'
      uniqueItems: true
    ProductOrSectorSpecificRule:
      type: object
      required:
      - operator
      - ruleNames
      properties:
        operator:
          $ref: '#/components/schemas/ProductOrSectorSpecificRuleOperator'
        ruleNames:
          $ref: '#/components/schemas/NonEmptyStringVec'
        otherOperatorName:
          anyOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - type: 'null'
    ProductOrSectorSpecificRuleOperator:
      type: string
      enum:
      - PEF
      - EPD International
      - Other
    NonEmptyStringVec:
      type: array
      items:
        type: string
        minLength: 1
      minItems: 1
      uniqueItems: true
    BiogenicAccountingMethodology:
      type: string
      enum:
      - PEF
      - ISO
      - GHPG
      - Quantis
    EmissionFactorDSSet:
      type: array
      items:
        type: object
        required:
        - name
        - version
        properties:
          name:
            $ref: '#/components/schemas/NonEmptyString'
          version:
            $ref: '#/components/schemas/NonEmptyString'
      minItems: 1
      uniqueItems: true
    EmissionFactorDS:
      type: object
      required:
      - name
      - version
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        version:
          $ref: '#/components/schemas/NonEmptyString'
    ExemptedEmissionsPercent:
      type: number
      format: double
      maximum: 5
      minimum: 0
    Percent:
      type: number
      format: double
      maximum: 100
      minimum: 0
    DataQualityIndicators:
      description: Data Type "DataQualityIndicators" of Spec Version 2
      type: object
      required:
      - completenessDQR
      - coveragePercent
      - geographicalDQR
      - reliabilityDQR
      - technologicalDQR
      - temporalDQR
      properties:
        coveragePercent:
          $ref: '#/components/schemas/Percent'
        technologicalDQR:
          $ref: '#/components/schemas/FloatBetween1And3'
        temporalDQR:
          $ref: '#/components/schemas/FloatBetween1And3'
        geographicalDQR:
          $ref: '#/components/schemas/FloatBetween1And3'
        completenessDQR:
          $ref: '#/components/schemas/FloatBetween1And3'
        reliabilityDQR:
          $ref: '#/components/schemas/FloatBetween1And3'
    FloatBetween1And3:
      type: number
      format: float
      maximum: 3
      minimum: 1
    Assurance:
      description: Data Type "Assurance" of Spec Version 2
      type: object
      required:
      - assurance
      - providerName
      properties:
        assurance:
          type: boolean
        coverage:
          $ref: '#/components/schemas/AssuranceCoverage'
        level:
          $ref: '#/components/schemas/AssuranceLevel'
        boundary:
          $ref: '#/components/schemas/AssuranceBoundary'
        providerName:
          type: string
        completedAt:
          type: string
          format: date-time
        standardName:
          type: string
        comments:
          type: string
    AssuranceCoverage:
      type: string
      enum:
      - corporate level
      - product line
      - PCF system
      - product level
    AssuranceLevel:
      type: string
      enum:
      - limited
      - reasonable
    AssuranceBoundary:
      type: string
      enum:
      - Gate-to-Gate
      - Cradle-to-Gate
    UNRegionOrSubregion:
      description: List of UN regions and subregions
      type: string
      enum:
      - Africa
      - Americas
      - Asia
      - Europe
      - Oceania
      - Australia and New Zealand
      - Central Asia
      - Eastern Asia
      - Eastern Europe
      - Latin America and the Caribbean
      - Melanesia
      - Micronesia
      - Northern Africa
      - Northern America
      - Northern Europe
      - Polynesia
      - South-eastern Asia
      - Southern Asia
      - Southern Europe
      - Sub-Saharan Africa
      - Western Asia
      - Western Europe
    ISO3166CC:
      type: string
    BadRequest:
      description: Response with an error code of `BadRequest`. See Chapter "Error
        Codes" of the Tech Specs for mor details.
      type: object
      required:
      - code
      - message
      properties:
        message:
          type: string
        code:
          type: string
    AccessDenied:
      description: Response with an error code of `AccessDenied`. See Chapter "Error
        Codes" of the Tech Specs for mor details.
      type: object
      required:
      - code
      - message
      properties:
        message:
          type: string
        code:
          type: string
    PathfinderEvent:
      description: possible contents of `data` property of events - see tech specs
        section 6 for details
      type: object
      oneOf:
      - description: "the contents of the `data` field of a `PF Update Event` – see
          Tech Specs section 6.8.3"
        type: object
        required:
        - data
        - type
        properties:
          type:
            type: string
            enum:
            - org.wbcsd.pathfinder.ProductFootprint.Published.v1
          data:
            $ref: '#/components/schemas/PFUpdateEventBody'
      - description: "the contents of the `data` field of a `PF Request Event` – see
          Tech Specs section 6.8.4.1"
        type: object
        required:
        - data
        - type
        properties:
          type:
            type: string
            enum:
            - org.wbcsd.pathfinder.ProductFootprintRequest.Created.v1
          data:
            $ref: '#/components/schemas/PFRequestEventBody'
      required:
      - id
      - source
      - specversion
      - time
      properties:
        specversion:
          type: string
        id:
          type: string
        source:
          type: string
        time:
          type: string
          format: date-time
    PFUpdateEventBody:
      type: object
      required:
      - pfIds
      properties:
        pfIds:
          type: array
          items:
            type: string
            format: uuid
    PFRequestEventBody:
      type: object
      required:
      - pf
      properties:
        pf: {}
        comment:
          type: string
  securitySchemes:
    BearerAuth:
      description: OAuth2 Client Credentials Grant (RFC6749 4.4)
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '/2/auth/token'
          scopes:
            footprint:list: Ability to list footprints
            footprint:read: Ability to access individual footprints
